# dormitorio.yaml
substitutions:
  device_name: fan-rack-dormitorio
  friendly_name: "FanRack Dormitorio"
  # Si usas pines diferentes, descomenta y cambia esto:
  # pin_pwm: "GPIO25" 

packages:
  base_logic: !include common/base_fan_rack.yaml

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

# Credenciales y API (se mantienen en el archivo individual por seguridad)
api:
  encryption:
    key: !secret api_encryption_key
ota:
  - platform: esphome
    password: !secret ota_password
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: !secret wifi_ap_ssid
    password: !secret wifi_ap_password